### hello {reprograma}

GET http://localhost:3000

### Criando usuário

POST http://localhost:3000/users
content-type: application/json

{
  "name":"Laura Barbosa",
  "email": "laura@gmail.com",
  "password": "15985lS!",
  "yearOfBirth": 1997 
}

### Criando outro usuário
POST http://localhost:3000/users
content-type: application/json

{
  "name":"Carlos Maia",
  "email": "cm@gmail.com",
  "password": "15896lS!",
  "yearOfBirth": 2004 
}

### Encontrando todos os usuários
GET http://localhost:3000/users


### Encontrando um usuário
GET http://localhost:3000/users/cm@gmail.com


### Modificar o peso
PATCH http://localhost:3000/users/cm@gmail.com

{
  "weight": 60
}

### Deletar usuário
DELETE http://localhost:3000/users/cm@gmail.com

