### hello {reprograma}

GET http://localhost:3000

### Criando usuário

POST http://localhost:3000/users
content-type: application/json

{
  "name":"Laura Barbosa",
  "email": "laura@gmail.com",
  "password": "15985lS!",
  "yearOfBirth": 1997 
}

### Criando outro usuário
POST http://localhost:3000/users
content-type: application/json

{
  "name":"Carla Luiza",
  "email": "cl@gmail.com",
  "password": "15896lS!",
  "yearOfBirth": 2004 
}

### Encontrando todos os usuários
GET http://localhost:3000/users


### Encontrando um usuário
GET http://localhost:3000/users/cm@gmail.com


### Deletar usuário
DELETE http://localhost:3000/users/cl@gmail.com

### fazer uma nova requisição 
POST  http://localhost:3000/localizacoes
content-type: application/json

{
  "city": "Campina Grande",
  "state": "PB"
}

### Modificar o apenas o peso do usuário
PATCH http://localhost:3000/water-calculator/hgd@gmail.com
content-type: application/json

{
  "weight": 50
}
